import type { Meal } from "./types"

export const mealsData: Meal[] = [
  {
    id: "1",
    name: "Owsianka z owocami",
    description: "Kremowa owsianka z świeżymi owocami i miodem. Idealna na energetyczny start dnia.",
    image: "/oatmeal-with-fresh-berries-and-honey-breakfast.jpg",
    category: "breakfast",
    tags: ["Wegetariańskie", "Wysokobiałkowe"],
    recipe: {
      ingredients: [
        "100g płatków owsianych",
        "250ml mleka",
        "1 łyżka miodu",
        "Garść świeżych jagód",
        "1 banan",
        "Szczypta cynamonu",
      ],
      instructions: [
        "Zagotuj mleko w garnku",
        "Dodaj płatki owsiane i gotuj na małym ogniu 5 minut",
        "Przełóż do miski i dodaj miód",
        "Udekoruj owocami i posyp cynamonem",
      ],
      prepTime: "5 min",
      cookTime: "10 min",
      servings: 1,
    },
  },
  {
    id: "2",
    name: "Jajecznica na bekonie",
    description: "Klasyczna jajecznica z chrupiącym bekonem i szczypiorkiem. Sycące śniadanie.",
    image: "/scrambled-eggs-with-crispy-bacon-breakfast.jpg",
    category: "breakfast",
    tags: ["Wysokobiałkowe", "Keto", "Bezglutenowe"],
    recipe: {
      ingredients: ["3 jajka", "4 plastry bekonu", "Łyżka masła", "Sól i pieprz", "Świeży szczypiorek"],
      instructions: [
        "Podsmaż bekon na patelni aż będzie chrupiący",
        "Na osobnej patelni rozpuść masło",
        "Wbij jajka i mieszaj delikatnie",
        "Dopraw solą i pieprzem",
        "Podawaj z bekonem i szczypiorkiem",
      ],
      prepTime: "5 min",
      cookTime: "10 min",
      servings: 1,
    },
  },
  {
    id: "3",
    name: "Smoothie bowl",
    description: "Orzeźwiające smoothie bowl z granolą i owocami. Lekkie i pełne witamin.",
    image: "/colorful-smoothie-bowl-with-granola-and-fruits.jpg",
    category: "breakfast",
    tags: ["Wegańskie", "Wegetariańskie", "Bezglutenowe"],
    recipe: {
      ingredients: [
        "1 mrożony banan",
        "100g mrożonych malin",
        "100ml mleka kokosowego",
        "Granola",
        "Świeże owoce do dekoracji",
        "Nasiona chia",
      ],
      instructions: [
        "Zblenduj banana, maliny i mleko kokosowe",
        "Przelej do miski",
        "Udekoruj granolą, owocami i nasionami chia",
      ],
      prepTime: "10 min",
      cookTime: "0 min",
      servings: 1,
    },
  },
  {
    id: "4",
    name: "Spaghetti Bolognese",
    description: "Klasyczne włoskie spaghetti z aromatycznym sosem mięsnym. Rodzinna klasyka.",
    image: "/spaghetti-bolognese-with-meat-sauce-italian.jpg",
    category: "lunch",
    tags: ["Wysokobiałkowe"],
    recipe: {
      ingredients: [
        "300g spaghetti",
        "400g mielonej wołowiny",
        "1 puszka pomidorów",
        "1 cebula",
        "2 ząbki czosnku",
        "Oregano, bazylia",
        "Parmezan",
      ],
      instructions: [
        "Podsmaż cebulę i czosnek na oliwie",
        "Dodaj mięso i smaż aż się zarumieni",
        "Wlej pomidory i dopraw ziołami",
        "Gotuj 20 minut na wolnym ogniu",
        "Ugotuj makaron al dente",
        "Podawaj z parmezanem",
      ],
      prepTime: "15 min",
      cookTime: "30 min",
      servings: 4,
    },
  },
  {
    id: "5",
    name: "Buddha Bowl",
    description: "Zdrowa miska pełna warzyw, quinoi i humusu. Idealna na lekki lunch.",
    image: "/buddha-bowl-with-quinoa-vegetables-hummus.jpg",
    category: "lunch",
    tags: ["Wegańskie", "Wegetariańskie", "Bezglutenowe", "Niskokaloryczne"],
    recipe: {
      ingredients: [
        "150g quinoi",
        "1 awokado",
        "Garść szpinaku",
        "Ciecierzyca",
        "Marchewka",
        "Hummus",
        "Oliwa z oliwek",
      ],
      instructions: [
        "Ugotuj quinoę według instrukcji",
        "Pokrój warzywa",
        "Ułóż wszystko w misce",
        "Dodaj hummus i polej oliwą",
      ],
      prepTime: "15 min",
      cookTime: "20 min",
      servings: 2,
    },
  },
  {
    id: "6",
    name: "Kurczak curry",
    description: "Aromatyczne curry z kurczakiem i warzywami w kremowym sosie kokosowym.",
    image: "/chicken-curry-with-coconut-milk-and-vegetables.jpg",
    category: "lunch",
    tags: ["Bezglutenowe", "Bez laktozy", "Wysokobiałkowe"],
    recipe: {
      ingredients: [
        "500g piersi z kurczaka",
        "400ml mleka kokosowego",
        "2 łyżki pasty curry",
        "Papryka",
        "Cukinia",
        "Ryż basmati",
      ],
      instructions: [
        "Pokrój kurczaka w kostkę i obsmaż",
        "Dodaj pastę curry i warzywa",
        "Wlej mleko kokosowe",
        "Gotuj 15 minut",
        "Podawaj z ryżem",
      ],
      prepTime: "15 min",
      cookTime: "25 min",
      servings: 4,
    },
  },
  {
    id: "7",
    name: "Łosoś z warzywami",
    description: "Pieczony łosoś z grillowanymi warzywami. Zdrowa i elegancka kolacja.",
    image: "/baked-salmon-with-roasted-vegetables-dinner.jpg",
    category: "dinner",
    tags: ["Bezglutenowe", "Bez laktozy", "Keto", "Wysokobiałkowe", "Niskokaloryczne"],
    recipe: {
      ingredients: ["2 filety z łososia", "Brokuły", "Cukinia", "Papryka", "Cytryna", "Oliwa z oliwek", "Rozmaryn"],
      instructions: [
        "Rozgrzej piekarnik do 200°C",
        "Ułóż warzywa na blasze i polej oliwą",
        "Połóż łososia i skrop cytryną",
        "Piecz 20-25 minut",
      ],
      prepTime: "10 min",
      cookTime: "25 min",
      servings: 2,
    },
  },
  {
    id: "8",
    name: "Risotto z grzybami",
    description: "Kremowe risotto z aromatycznymi grzybami leśnymi i parmezanem.",
    image: "/images/menu/risotto.png",
    category: "dinner",
    tags: ["Wegetariańskie"],
    recipe: {
      ingredients: [
        "300g ryżu arborio",
        "300g grzybów",
        "1 szalotka",
        "100ml białego wina",
        "1l bulionu warzywnego",
        "Parmezan",
        "Masło",
      ],
      instructions: [
        "Podsmaż szalotkę na maśle",
        "Dodaj ryż i smaż 2 minuty",
        "Wlej wino i poczekaj aż wyparuje",
        "Dodawaj bulion porcjami, mieszając",
        "Na koniec dodaj grzyby i parmezan",
      ],
      prepTime: "10 min",
      cookTime: "30 min",
      servings: 4,
    },
  },
  {
    id: "9",
    name: "Tacos z wołowiną",
    description: "Pikantne tacos z soczystą wołowiną, salsą i świeżymi warzywami.",
    image: "/beef-tacos-with-salsa-and-fresh-vegetables-mexican.jpg",
    category: "dinner",
    tags: ["Wysokobiałkowe"],
    recipe: {
      ingredients: [
        "400g mielonej wołowiny",
        "Tortille kukurydziane",
        "Salsa",
        "Sałata",
        "Pomidory",
        "Awokado",
        "Śmietana",
        "Przyprawa taco",
      ],
      instructions: [
        "Podsmaż mięso z przyprawą taco",
        "Podgrzej tortille",
        "Pokrój warzywa",
        "Złóż tacos z mięsem i warzywami",
        "Dodaj salsę i śmietanę",
      ],
      prepTime: "15 min",
      cookTime: "15 min",
      servings: 4,
    },
  },
  {
    id: "10",
    name: "Tosty z awokado",
    description: "Chrupiące tosty z kremowym awokado i jajkiem sadzonym. Trendy i pyszne.",
    image: "/avocado-toast-with-poached-egg-breakfast.jpg",
    category: "breakfast",
    tags: ["Wegetariańskie", "Wysokobiałkowe"],
    recipe: {
      ingredients: ["2 kromki chleba", "1 dojrzałe awokado", "2 jajka", "Sól, pieprz", "Chili płatki", "Sok z cytryny"],
      instructions: [
        "Opiecz chleb w tosterze",
        "Rozgnieć awokado i dopraw",
        "Usmaż jajka sadzone",
        "Połóż awokado na tostach",
        "Dodaj jajka i posyp chili",
      ],
      prepTime: "5 min",
      cookTime: "5 min",
      servings: 1,
    },
  },
  {
    id: "11",
    name: "Sałatka grecka",
    description: "Orzeźwiająca sałatka z fetą, oliwkami i chrupiącymi warzywami.",
    image: "/greek-salad-with-feta-cheese-olives-cucumber.jpg",
    category: "lunch",
    tags: ["Wegetariańskie", "Bezglutenowe", "Niskokaloryczne", "Keto"],
    recipe: {
      ingredients: [
        "Ogórek",
        "Pomidory",
        "Czerwona cebula",
        "Ser feta",
        "Oliwki kalamata",
        "Oliwa z oliwek",
        "Oregano",
      ],
      instructions: ["Pokrój warzywa w kostkę", "Dodaj pokruszoną fetę", "Wrzuć oliwki", "Polej oliwą i posyp oregano"],
      prepTime: "10 min",
      cookTime: "0 min",
      servings: 2,
    },
  },
  {
    id: "12",
    name: "Zupa krem z dyni",
    description: "Aksamitna zupa z dyni z nutą imbiru i prażonymi pestkami.",
    image: "/creamy-pumpkin-soup-with-seeds-autumn.jpg",
    category: "dinner",
    tags: ["Wegańskie", "Wegetariańskie", "Bezglutenowe", "Bez laktozy", "Niskokaloryczne"],
    recipe: {
      ingredients: [
        "1kg dyni",
        "1 cebula",
        "2 ząbki czosnku",
        "Imbir",
        "1l bulionu warzywnego",
        "Pestki dyni",
        "Śmietanka kokosowa",
      ],
      instructions: [
        "Podsmaż cebulę i czosnek",
        "Dodaj pokrojoną dynię",
        "Wlej bulion i gotuj 20 minut",
        "Zblenduj na gładki krem",
        "Podawaj z pestkami i śmietanką",
      ],
      prepTime: "15 min",
      cookTime: "30 min",
      servings: 6,
    },
  },
]
